import Head from 'next/head';
import styles from './Index.module.css';
import Image from 'next/image';
import { landingbg } from '../../public/img';
import { th1 } from '/public/img/th';
import { th2, th3, th4, th5, th6 } from '../../public/img/th';

const ths = [
	{
		name: 'th1',
		img: th1,
	},
	{
		name: 'th2',
		img: th2,
	},
	{
		name: 'th3',
		img: th3,
	},
	{
		name: 'th4',
		img: th4,
	},
	{
		name: 'th5',
		img: th5,
	},
	{
		name: 'th6',
		img: th6,
	},
];

export default function Home() {
	return (
		<>
			<Head>
				<title>Home | Clash of Clans Enciclopedya</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<Image
					src={landingbg}
					fill
					className={styles.img}
					priority
					alt={'clash of clans background'}
				/>
				<section className={styles.thsection}>
					{ths.map((item, i) => {
						return (
							<>
								<div className={styles.thimgcontainer}>
									<Image
										src={item.img}
										alt={item.name}
										fill
										key={i}
										className={styles.thimg}
									/>
								</div>
							</>
						);
					})}
				</section>
			</main>
		</>
	);
}
