import Head from 'next/head';
// import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import Image from 'next/image';
import styles from './Index.module.css';
import { wallpedia, wallblog, wallshop, wallcontact } from '../../public/img';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<Link href={'/wiki'} className={styles.wiki}>
					<Image
						src={wallpedia}
						className={styles.img}
						alt={'clash of clans landscape'}
						priority={true}
						width={1000}
						height={1000}
						quality={50}
					/>
					<h2 className={styles.title}>Wiki</h2>
				</Link>
				<Link href={'/blog'} className={styles.blog}>
					<Image
						src={wallblog}
						className={styles.img}
						alt={'clash of clans capital mountain landscape'}
						priority={true}
						width={1000}
						height={1000}
						quality={50}
					/>
					<h2 className={styles.title}>Blog</h2>
				</Link>
				<Link href={'/shop'} className={styles.shop}>
					<Image
						src={wallshop}
						className={styles.img}
						alt={'clash of clans image of three barbarians figthing a cannon'}
						priority={true}
						width={1000}
						height={1000}
						quality={50}
					/>
					<h2 className={styles.title}>Shop</h2>
				</Link>
				<Link href={'/contact'} className={styles.contact}>
					<Image
						src={wallcontact}
						className={styles.img}
						alt={'clash of clans image of three barbarians figthing a cannon'}
						priority={true}
						width={1000}
						height={1000}
						quality={50}
					/>
					<h2 className={styles.title}>Contact</h2>
				</Link>
			</main>
		</>
	);
}
